DECLARE @startDate DATE = '2024-11-01',
    @endDate DATE = '2024-11-30'

SELECT 'WEC AICM' AS COLECCION,
    C1280      AS GUIA_MASTER,
    C1281      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1279      AS CODIGO_BARRA_CAJA,
    C1282      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1283      AS CODIGO_BARRAS_EXPEDIENTE,
    C1315      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000008 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1286      AS GUIA_MASTER,
    C1287      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1285      AS CODIGO_BARRA_CAJA,
    C1288      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1289      AS CODIGO_BARRAS_EXPEDIENTE,
    C1316      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000009 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1292      AS GUIA_MASTER,
    C1293      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1291      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1294      AS FECHA,
    C1295      AS CODIGO_BARRAS_EXPEDIENTE,
    C1317      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000A C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1322      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1330      AS FECHA,
    C1323      AS CODIGO_BARRAS_EXPEDIENTE,
    C1324      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000G C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1299      AS GUIA_MASTER,
    C1300      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1298      AS CODIGO_BARRA_CAJA,
    C1301      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1302      AS CODIGO_BARRAS_EXPEDIENTE,
    C1318      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000D C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1305      AS GUIA_MASTER,
    C1306      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1304      AS CODIGO_BARRA_CAJA,
    C1307      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1308      AS CODIGO_BARRAS_EXPEDIENTE,
    C1319      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000E C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1311      AS GUIA_MASTER,
    C1312      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1310      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1313      AS FECHA,
    C1314      AS CODIGO_BARRAS_EXPEDIENTE,
    C1320      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000F C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1326      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1331      AS FECHA,
    C1327      AS CODIGO_BARRAS_EXPEDIENTE,
    C1328      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000H C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate