SELECT *
    FROM G_CAMPOS_01C0000007 GC
             INNER JOIN G_DOCUMENTOS GD ON GC.GID = GD.GID
             INNER JOIN G_PAGINAS GP ON GD.GID = GP.GID_DOCUMENTO

SELECT * FROM G_CAMPOS
WHERE GID = '01C0000007'