UPDATE NADRO.dbo.Datos_Contratos
SET Empresa = 'FARMACIAS BELLA VISTA, S.A.P.I. DE C.V.'
WHERE Empresa = 'FARMACIA BELLA VISTA, S.A.P.I. DE C.V.'

UPDATE NADRO.dbo.Datos_Arrendamiento
SET Empresa = 'FARMACIAS BELLA VISTA, S.A.P.I. DE C.V.'
    WHERE Empresa = 'FARMACIA BELLA VISTA, S.A.P.I. DE C.V.'