SELECT A.GID
     , GID_COLECCION
     , SUBSTRING(A.GID, 4, 1) + '\' + SUBSTRING(A.GID, 5, 2) + '\' + SUBSTRING(A.GID, 7, 2) + '\' +
       SUBSTRING(A.GID, 4, 20) +
       '.' + EXTENSION AS RUTA
    FROM G_PAGINAS A
             INNER JOIN G_DOCUMENTOS B ON A.GID_DOCUMENTO = B.GID

SELECT GID_COLECCION + '\' + SUBSTRING(A.GID, 4, 1) + '\' + SUBSTRING(A.GID, 5, 2) + '\' + SUBSTRING(A.GID, 7, 2) AS RUTA
    FROM G_PAGINAS A
             INNER JOIN G_DOCUMENTOS B ON A.GID_DOCUMENTO = B.GID
    GROUP BY GID_COLECCION + '\' + SUBSTRING(A.GID, 4, 1) + '\' + SUBSTRING(A.GID, 5, 2) + '\' + SUBSTRING(A.GID, 7, 2) 