SELECT * FROM G_DOCUMENTOS
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_DOCUMENTOS
WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_PAGINAS
         WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_PAGINAS
         WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09'  OR CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-10'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP (1)* FROM G_PAGINAS
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_PAGINAS
         WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09' OR CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-10'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP(1)* FROM G_PAGINAS
         WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09' OR CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-10'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP(1) * FROM G_PAGINAS
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP(1) * FROM G_PAGINAS
         WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_DOCUMENTOS
WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09' OR CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-10'
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_DOCUMENTOS
SET FECHA_CREACION = DATEADD(DAY, -9, FECHA_CREACION)
    WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09'
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_PAGINAS
SET FECHA_CREACION = DATEADD(DAY, -9, FECHA_CREACION)
    WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-10-09'
;-- -. . -..- - / . -. - .-. -.--
DECLARE @startDate DATE = '2024-09-01',
    @endDate DATE = '2024-09-30'

SELECT 'WEC AICM' AS COLECCION,
    C1280      AS GUIA_MASTER,
    C1281      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1279      AS CODIGO_BARRA_CAJA,
    C1282      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1283      AS CODIGO_BARRAS_EXPEDIENTE,
    C1315      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000008 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1286      AS GUIA_MASTER,
    C1287      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1285      AS CODIGO_BARRA_CAJA,
    C1288      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1289      AS CODIGO_BARRAS_EXPEDIENTE,
    C1316      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000009 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1292      AS GUIA_MASTER,
    C1293      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1291      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1294      AS FECHA,
    C1295      AS CODIGO_BARRAS_EXPEDIENTE,
    C1317      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000A C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1322      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1330      AS FECHA,
    C1323      AS CODIGO_BARRAS_EXPEDIENTE,
    C1324      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000G C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1299      AS GUIA_MASTER,
    C1300      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1298      AS CODIGO_BARRA_CAJA,
    C1301      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1302      AS CODIGO_BARRAS_EXPEDIENTE,
    C1318      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000D C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1305      AS GUIA_MASTER,
    C1306      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1304      AS CODIGO_BARRA_CAJA,
    C1307      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1308      AS CODIGO_BARRAS_EXPEDIENTE,
    C1319      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000E C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1311      AS GUIA_MASTER,
    C1312      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1310      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1313      AS FECHA,
    C1314      AS CODIGO_BARRAS_EXPEDIENTE,
    C1320      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000F C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1326      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1331      AS FECHA,
    C1327      AS CODIGO_BARRAS_EXPEDIENTE,
    C1328      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000H C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_COLECCIONES
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_COLECCIONES
WHERE COLECCION_TIPO = 'D'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_campos_01C0000008
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_campos_01C0000008
WHERE GID = '01D003GGAD'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_CAMPOS
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_CAMPOS
WHERE CAMPO_ID = 1288
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_USUARIOS
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_DOCUMENTOS
WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-11-01' OR CONVERT(DATE, FECHA_CREACION, 103) = '2024-11-12'
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_DOCUMENTOS
SET FECHA_CREACION = DATEADD(DAY, -11, FECHA_CREACION)
    WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-11-11'
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_PAGINAS
SET FECHA_CREACION = DATEADD(DAY, -11, FECHA_CREACION)
    WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-11-11'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP(1) * FROM G_PAGINAS
         WHERE CONVERT(DATE, FECHA_CREACION, 103) = '2024-11-11'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_DOCUMENTOS
WHERE CONVERT(DATE, FECHA_CREACION, 103) BETWEEN '2024-11-01' AND '2024-11-12'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP (1) *
    FROM G_PAGINAS
    WHERE CONVERT(DATE, FECHA_CREACION, 103) BETWEEN '2024-11-01' AND '2024-11-12'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP (1) *
    FROM G_PAGINAS
    WHERE FECHA_CREACION >= '2024-11-01' AND FECHA_CREACION < '2024-11-13'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP (1) *
    FROM G_PAGINAS
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP (1) *
    FROM G_PAGINAS
    WHERE FECHA_CREACION >= '2024-11-01 00:00:00' AND FECHA_CREACION < '2024-11-13 00:00:00'
;-- -. . -..- - / . -. - .-. -.--
SELECT TOP (1) *
    FROM G_PAGINAS
    WHERE convert(DATE, FECHA_CREACION,103 ) = '2024-11-11'
;-- -. . -..- - / . -. - .-. -.--
DECLARE @startDate DATE = '2024-10-01',
    @endDate DATE = '2024-10-31'

SELECT 'WEC AICM' AS COLECCION,
    C1280      AS GUIA_MASTER,
    C1281      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1279      AS CODIGO_BARRA_CAJA,
    C1282      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1283      AS CODIGO_BARRAS_EXPEDIENTE,
    C1315      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000008 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1286      AS GUIA_MASTER,
    C1287      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1285      AS CODIGO_BARRA_CAJA,
    C1288      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1289      AS CODIGO_BARRAS_EXPEDIENTE,
    C1316      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000009 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1292      AS GUIA_MASTER,
    C1293      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1291      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1294      AS FECHA,
    C1295      AS CODIGO_BARRAS_EXPEDIENTE,
    C1317      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000A C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1322      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1330      AS FECHA,
    C1323      AS CODIGO_BARRAS_EXPEDIENTE,
    C1324      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000G C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1299      AS GUIA_MASTER,
    C1300      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1298      AS CODIGO_BARRA_CAJA,
    C1301      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1302      AS CODIGO_BARRAS_EXPEDIENTE,
    C1318      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000D C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1305      AS GUIA_MASTER,
    C1306      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1304      AS CODIGO_BARRA_CAJA,
    C1307      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1308      AS CODIGO_BARRAS_EXPEDIENTE,
    C1319      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000E C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1311      AS GUIA_MASTER,
    C1312      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1310      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1313      AS FECHA,
    C1314      AS CODIGO_BARRAS_EXPEDIENTE,
    C1320      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000F C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1326      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1331      AS FECHA,
    C1327      AS CODIGO_BARRAS_EXPEDIENTE,
    C1328      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000H C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
;-- -. . -..- - / . -. - .-. -.--
SELECT c1278
    FROM G_CAMPOS_01C0000008
    WHERE c1278 COLLATE Latin1_General_BIN LIKE '%[a-z]%'
;-- -. . -..- - / . -. - .-. -.--
SELECT c1279
    FROM G_CAMPOS_01C0000008
    WHERE c1278 COLLATE Latin1_General_BIN LIKE '%[a-z]%'
;-- -. . -..- - / . -. - .-. -.--
SELECT gid, c1278, c1279, c1280, c1281, c1282, c1283, c1315
    FROM G_CAMPOS_01C0000008
    WHERE c1279 COLLATE Latin1_General_BIN LIKE '%[a-z]%'
;-- -. . -..- - / . -. - .-. -.--
SELECT gid, c1278, c1279, c1280, c1281, c1282, c1283, c1315
    FROM G_CAMPOS_01C0000008
    WHERE c1280 COLLATE Latin1_General_BIN LIKE '%[a-z]%'
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_CAMPOS_01C000000D
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM G_CAMPOS_01C000000I
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C000000I
SET C1337 = UPPER(C1337)
  , C1338 = UPPER(C1338)
  , C1339 = UPPER(C1339)
  , C1340 = UPPER(C1340)
  , C1341 = UPPER(C1341)
  , C1342 = UPPER(C1342)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C000000E
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C000000E
SET C1303 = UPPER(C1303),
    C1304 = UPPER(C1304),
    C1305 = UPPER(C1305),
    C1306 = UPPER(C1306),
    C1307 = UPPER(C1307),
    C1308 = UPPER(C1308)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C000000D
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C000000D
SET C1297 = UPPER(C1297)
  , C1298 = UPPER(C1298)
  , C1299 = UPPER(C1299)
  , C1300 = UPPER(C1300)
  , C1301 = UPPER(C1301)
  , C1302 = UPPER(C1302)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C000000G
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C000000G
SET C1321 = UPPER(C1321)
  , C1322 = UPPER(C1322)
  , C1323 = UPPER(C1323)
  , C1324 = UPPER(C1324)
  , C1329 = UPPER(C1329)
  , C1330 = UPPER(C1330)
  , C1333 = UPPER(C1333)
  , C1335 = UPPER(C1335)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C0000009
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C0000009
SET C1284 = UPPER(C1284)
  , C1285 = UPPER(C1285)
  , C1286 = UPPER(C1286)
  , C1287 = UPPER(C1287)
  , C1288 = UPPER(C1288)
  , C1289 = UPPER(C1289)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C0000008
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C0000008
SET C1278 = UPPER(C1278),
    C1279 = UPPER(C1279),
    C1280 = UPPER(C1280),
    C1281 = UPPER(C1281),
    C1282 = UPPER(C1282),
    C1283 = UPPER(C1283)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C0000003
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C0000003
SET C1259 = UPPER(C1259),
    C1260 = UPPER(C1260),
    C1261 = UPPER(C1261),
    C1262 = UPPER(C1262),
    C1263 = UPPER(C1263),
    C1264 = UPPER(C1264)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C0000004
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C0000004
SET C1265 = UPPER(C1265)
  , C1266 = UPPER(C1266)
  , C1267 = UPPER(C1267)
  , C1268 = UPPER(C1268)
  , C1269 = UPPER(C1269)
  , C1270 = UPPER(C1270)
;-- -. . -..- - / . -. - .-. -.--
SELECT *
    FROM G_CAMPOS_01C0000005
;-- -. . -..- - / . -. - .-. -.--
UPDATE G_CAMPOS_01C0000005
SET C1271 = UPPER(C1271)
  , C1272 = UPPER(C1272)
  , C1273 = UPPER(C1273)
  , C1274 = UPPER(C1274)
  , C1275 = UPPER(C1275)
  , C1276 = UPPER(C1276)
  , C1336 = UPPER(C1336)
;-- -. . -..- - / . -. - .-. -.--
DECLARE @startDate DATE = '2024-11-01',
    @endDate DATE = '2024-11-30'

SELECT 'WEC AICM' AS COLECCION,
    C1280      AS GUIA_MASTER,
    C1281      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1279      AS CODIGO_BARRA_CAJA,
    C1282      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1283      AS CODIGO_BARRAS_EXPEDIENTE,
    C1315      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000008 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1286      AS GUIA_MASTER,
    C1287      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1285      AS CODIGO_BARRA_CAJA,
    C1288      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1289      AS CODIGO_BARRAS_EXPEDIENTE,
    C1316      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C0000009 C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    C1292      AS GUIA_MASTER,
    C1293      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1291      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1294      AS FECHA,
    C1295      AS CODIGO_BARRAS_EXPEDIENTE,
    C1317      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000A C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AICM' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1322      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1330      AS FECHA,
    C1323      AS CODIGO_BARRAS_EXPEDIENTE,
    C1324      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000G C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1299      AS GUIA_MASTER,
    C1300      AS GUIA_HOUSE,
    'Entrada'  AS COLLECCION_DOCUMENTAL,
    C1298      AS CODIGO_BARRA_CAJA,
    C1301      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1302      AS CODIGO_BARRAS_EXPEDIENTE,
    C1318      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000D C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1305      AS GUIA_MASTER,
    C1306      AS GUIA_HOUSE,
    'Salida'   AS COLLECCION_DOCUMENTAL,
    C1304      AS CODIGO_BARRA_CAJA,
    C1307      AS NUMERO_PAPELETA_O_FACTURA,
    NULL       AS FECHA,
    C1308      AS CODIGO_BARRAS_EXPEDIENTE,
    C1319      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000E C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    C1311      AS GUIA_MASTER,
    C1312      AS GUIA_HOUSE,
    'Otro'     AS COLLECCION_DOCUMENTAL,
    C1310      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1313      AS FECHA,
    C1314      AS CODIGO_BARRAS_EXPEDIENTE,
    C1320      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000F C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate
UNION ALL
SELECT 'WEC AIFA' AS COLECCION,
    ''         AS GUIA_MASTER,
    ''         AS GUIA_HOUSE,
    'Transito' AS COLLECCION_DOCUMENTAL,
    C1326      AS CODIGO_BARRA_CAJA,
    ''         AS NUMERO_PAPELETA_O_FACTURA,
    C1331      AS FECHA,
    C1327      AS CODIGO_BARRAS_EXPEDIENTE,
    C1328      AS FECHA_RECOLECCION,
    P.IMAGENES,
    P.FECHA_CREACION,
    P.CREADO_POR
    FROM G_CAMPOS_01C000000H C
             INNER JOIN G_PAGINAS as P ON C.GID = P.GID_DOCUMENTO
    WHERE CONVERT(DATE, P.FECHA_CREACION, 103) BETWEEN @startDate AND @endDate